name: "build-linux"
on:
  release:
    types: ["published"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for package update
      uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-commit
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: update
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: "master"

    - name: Make Release Changes
      run: . .github/release-changes.sh "${{ github.event.release.tag_name }}"

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3

    - name: Restore dependencies
      run: yarn install

    - name: Build Typescript
      run: yarn build-tsc

    - name: Build for Linux
      run: yarn build-linux

    - name: Rename Deb File
      run: mv ./dist/*.deb ./dist/cpavalancheclient_${{ env.version }}.deb
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          ./dist/*.deb
          ./dist/*.AppImage
          ./dist/latest-linux.yml

    - name: "Upload Artifacts to Release"
      uses: "ncipollo/release-action@v1"
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "dist/*.deb,dist/*.AppImage,dist/latest-linux.yml"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
