name: "Release-MacOS"
on:
  release:
    types: ["published"]

jobs:
  publish:
    permissions: write-all
    runs-on: macos-latest

    steps:
    - name: Wait for package update
      uses: ivan-sre/action-wait-for-check@v5.0.0
      id: wait-for-commit
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: update
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: "main"

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Get corepack
      run: npm install -g corepack

    - name: Enable corepack
      run: corepack enable

    - name: Update yarn
      run: yarn install

    - name: Build Typescript
      run: yarn build-tsc

    - name: Build for MacOS
      run: yarn build-mac
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts_macos
        path: |
          ./dist/*.dmg
          ./dist/*.blockmap
          ./dist/*.zip
          ./dist/latest-mac.yml

    - name: "Upload Artifacts to Release"
      uses: "ncipollo/release-action@v1"
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "dist/*.dmg,dist/*.blockmap,dist/*.zip,dist/latest-mac.yml"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
